/*
 * This file is automatically generated by Qt Design Studio.
 * Do not change.
*/

#include <QtQml/qqmlextensionplugin.h>

Q_IMPORT_QML_PLUGIN(contentPlugin)
Q_IMPORT_QML_PLUGIN(DashboardPlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_VwgolfPlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_VolkslogoPlugin)

